### ISSUE TITLE
Need update to support Saleae Logic Pro 8

### ISSUE THREAD

**Issue by mfinlaySWI** [alejmrm/RFFEAnalyzer#1]
I had Saleae update and recompile the RFFEv1.0 analyzer .dll so that it would be recognized by their new Logic Pro 8 product.  However, the analyzer only provides a few annotations on the SDATA trace of a simulated signal and nothing for a real signal.  Additionally it does not provide any decoded data for either type of signal. Is there anything that can be done to allow this analyzer to provide some decoded data or trace annotations on the real signal? I've attached the two screenshots for reference. 

![rffe_readreg31_screenshot](https://cloud.githubusercontent.com/assets/9274127/4671108/736c7498-557d-11e4-8e1d-0608dd97aadd.png)
![rffe_simulation_screenshot](https://cloud.githubusercontent.com/assets/9274127/4671109/7372b54c-557d-11e4-976d-0828f3d62df5.png)

**Comment by alejmrm** [comment]
I don't have the hardware anymore, both the Logic and RFFE devices, but I would like to help you if you send me some log files, so I can use the Logic software to load the waveform and fix the issues reported by you. Is this possible? Also your configuration for the Analyzer and the Logic will help.

**Comment by mfinlaySWI** [comment]
Hi Alex,

Thanks for the offer to help.  Here is what I have got:

·         Logic software beta version 1.1.28 from here: https://www.saleae.com/downloads

·         RFFEAnalyzer.dll from Saleae (attached).

·         Two .logicdata log files (attached) which correspond to the two screenshots already posted.

·         My OS is Windows 7.

Regarding my configuration, do you mean Analyzer Settings as shown below?

[cid:image001.png@01CFF1EC.DC432EC0]

In addition, I have used the following other settings:

[cid:image002.png@01CFF1EE.F8087CD0]

[cid:image003.png@01CFF1EE.F8087CD0]

[cid:image004.png@01CFF1EE.F8087CD0]

Let me know if there is anything else I could provide that would be useful.

Cheers,
Mark

**Comment by alejmrm** [comment]
Mark--

I was not able to get the files from the email that you provided due probably github is not allowing the attachments to be resent. Please use my gmail account directly, with the same username as seem here in github.

Alex.

**Comment by alejmrm** [comment]
Latest commit, should fix all issues reported here, 
Commit version: 4bfcf85c2cf348ff74b33eb840dff37134badfeb
